id: P3B592C54
initial_creation_type: input
source_metadata:
  title: Wealth and Prosperity Series
  language: fr
  description: 'A selection of texts on the theme of wealth and prosperity including
    rites for summoning the spirit of prosperity or abundance (g.yang ''gugs):'
  volume:
    74a5f450d8164778a7d3e02998a4e528:
      title: Sang Offering to Yellow Jambhala
      parent: Offering
    40e0eaec57ba4e1194777a2d311e7dca:
      title: Great Clouds of First-Portion Offerings for Prosperity
      parent: Offering
    e333514a96a9496e981453d1ea3d9ab4:
      title: 'Summoning the Spirit of Abundance: A Rain of Flowers'
      parent: Summoning Prosperity
    8e551b64e7884dc7a8ad38c2ae6a399d:
      title: 'The Summoning Hook of Wish-Fulfilment: An Appeal for Prosperity'
      parent: Summoning Prosperity
    761411a3a22a47f89504539923eb4574:
      title: Summoning Prosperity
      parent: Summoning Prosperity
    556440439680432e8f16896dee2841c2:
      title: A Brief Prayer for Summoning Prosperity
      parent: Summoning Prosperity
    e0c8bca5bff5410690391799fdd840c5:
      title: Summoning the Spirit of Abundance - The Hook of Divine Substance
      parent: Summoning Prosperity
    90355c1569564396bc8d0a0f84909cb4:
      title: An Appeal for the Prosperity of Teaching and Studying the Five Major
        Scriptures
      parent: Summoning Prosperity
created_at: '2022-03-01T06:34:53.426126'
last_modified_at: '2022-03-01T06:34:53.426129'
